services:

# Container de Aplicação Laravel-1
  laravel-1:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    container_name: laravel-1
    restart: always
    tty: true
    environment:
      APP_ENV: ${APP_ENV}
      APP_KEY: ${APP_KEY}
      APP_DEBUG: ${APP_DEBUG}
      APP_URL: ${APP_URL}
      DB_HOST: mysql
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    volumes:
      - .:/var/www/laravel
    depends_on:
      - mysql
      - redis
    networks:
      - laravel_app
    command: >
      sh -c "
      echo '📦 Instalando dependências do Composer...' &&
      composer install --no-dev --optimize-autoloader &&
      
      echo '🔑 Gerando chave da aplicação...' &&
      php artisan key:generate &&
      
      echo '🗑 Limpando cache do Laravel...' &&
      php artisan config:clear &&
      php artisan cache:clear &&
      
      echo '⌛ Aguardando MySQL iniciar...' &&
      while ! mysqladmin ping -hmysql --silent; do sleep 1; done &&
      
      echo '⚡ Rodando migrations...' &&
      php artisan migrate --force &&
      
      echo '🔐 Publicando Laravel Sanctum...' &&
      php artisan vendor:publish --provider='Laravel\\Sanctum\\SanctumServiceProvider' &&
      
      echo '🌐 Configurando permissões...' &&
      chmod -R 775 storage bootstrap/cache &&
      chown -R www-data:www-data /var/www/laravel"


# Container de Aplicação Laravel-2
  laravel-2:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    container_name: laravel-2
    restart: always
    tty: true
    environment:
      APP_ENV: ${APP_ENV}
      APP_KEY: ${APP_KEY}
      APP_DEBUG: ${APP_DEBUG}
      APP_URL: ${APP_URL}
      DB_HOST: mysql
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    volumes:
      - .:/var/www/laravel
    depends_on:
      - mysql
      - redis
    networks:
      - laravel_app
    command: >
      sh -c "
      echo '📦 Instalando dependências do Composer...' &&
      composer install --no-dev --optimize-autoloader &&
      
      echo '🔑 Gerando chave da aplicação...' &&
      php artisan key:generate &&
      
      echo '🗑 Limpando cache do Laravel...' &&
      php artisan config:clear &&
      php artisan cache:clear &&
      
      echo '⌛ Aguardando MySQL iniciar...' &&
      while ! mysqladmin ping -hmysql --silent; do sleep 1; done &&
      
      echo '⚡ Rodando migrations...' &&
      php artisan migrate --force &&
      
      echo '🔐 Publicando Laravel Sanctum...' &&
      php artisan vendor:publish --provider='Laravel\\Sanctum\\SanctumServiceProvider' &&
      
      echo '🌐 Configurando permissões...' &&
      chmod -R 775 storage bootstrap/cache &&
      chown -R www-data:www-data /var/www/laravel"


# Container de Aplicação Laravel-3
  laravel-3:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    container_name: laravel-3
    restart: always
    tty: true
    environment:
      APP_ENV: ${APP_ENV}
      APP_KEY: ${APP_KEY}
      APP_DEBUG: ${APP_DEBUG}
      APP_URL: ${APP_URL}
      DB_HOST: mysql
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    volumes:
      - .:/var/www/laravel
    depends_on:
      - mysql
      - redis
    networks:
      - laravel_app
    command: >
      sh -c "
      echo '📦 Instalando dependências do Composer...' &&
      composer install --no-dev --optimize-autoloader &&
      
      echo '🔑 Gerando chave da aplicação...' &&
      php artisan key:generate &&
      
      echo '🗑 Limpando cache do Laravel...' &&
      php artisan config:clear &&
      php artisan cache:clear &&
      
      echo '⌛ Aguardando MySQL iniciar...' &&
      while ! mysqladmin ping -hmysql --silent; do sleep 1; done &&
      
      echo '⚡ Rodando migrations...' &&
      php artisan migrate --force &&
      
      echo '🔐 Publicando Laravel Sanctum...' &&
      php artisan vendor:publish --provider='Laravel\\Sanctum\\SanctumServiceProvider' &&
      
      echo '🌐 Configurando permissões...' &&
      chmod -R 775 storage bootstrap/cache &&
      chown -R www-data:www-data /var/www/laravel"


# Container de Aplicação Laravel-4
  laravel-4:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    container_name: laravel-4
    restart: always
    tty: true
    environment:
      APP_ENV: ${APP_ENV}
      APP_KEY: ${APP_KEY}
      APP_DEBUG: ${APP_DEBUG}
      APP_URL: ${APP_URL}
      DB_HOST: mysql
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    volumes:
      - .:/var/www/laravel
    depends_on:
      - mysql
      - redis
    networks:
      - laravel_app
    command: >
      sh -c "
      echo '📦 Instalando dependências do Composer...' &&
      composer install --no-dev --optimize-autoloader &&
      
      echo '🔑 Gerando chave da aplicação...' &&
      php artisan key:generate &&
      
      echo '🗑 Limpando cache do Laravel...' &&
      php artisan config:clear &&
      php artisan cache:clear &&
      
      echo '⌛ Aguardando MySQL iniciar...' &&
      while ! mysqladmin ping -hmysql --silent; do sleep 1; done &&
      
      echo '⚡ Rodando migrations...' &&
      php artisan migrate --force &&
      
      echo '🔐 Publicando Laravel Sanctum...' &&
      php artisan vendor:publish --provider='Laravel\\Sanctum\\SanctumServiceProvider' &&
      
      echo '🌐 Configurando permissões...' &&
      chmod -R 775 storage bootstrap/cache &&
      chown -R www-data:www-data /var/www/laravel"


# Container de Aplicação Laravel-5
  laravel-5:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    container_name: laravel-5
    restart: always
    tty: true
    environment:
      APP_ENV: ${APP_ENV}
      APP_KEY: ${APP_KEY}
      APP_DEBUG: ${APP_DEBUG}
      APP_URL: ${APP_URL}
      DB_HOST: mysql
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    volumes:
      - .:/var/www/laravel
    depends_on:
      - mysql
      - redis
    networks:
      - laravel_app
    command: >
      sh -c "
      echo '📦 Instalando dependências do Composer...' &&
      composer install --no-dev --optimize-autoloader &&
      
      echo '🔑 Gerando chave da aplicação...' &&
      php artisan key:generate &&
      
      echo '🗑 Limpando cache do Laravel...' &&
      php artisan config:clear &&
      php artisan cache:clear &&
      
      echo '⌛ Aguardando MySQL iniciar...' &&
      while ! mysqladmin ping -hmysql --silent; do sleep 1; done &&
      
      echo '⚡ Rodando migrations...' &&
      php artisan migrate --force &&
      
      echo '🔐 Publicando Laravel Sanctum...' &&
      php artisan vendor:publish --provider='Laravel\\Sanctum\\SanctumServiceProvider' &&
      
      echo '🌐 Configurando permissões...' &&
      chmod -R 775 storage bootstrap/cache &&
      chown -R www-data:www-data /var/www/laravel"


# Container de Aplicação React
  react:
    build:
      context: ../frontend  
      dockerfile: docker/php/Dockerfile
    container_name: react-container
    restart: always
    ports:
      - "5173:5173"
    volumes:
      - ../frontend:/app
      - /app/node_modules
    stdin_open: true
    tty: true
    depends_on:
      - nginx
    networks:
      - laravel_app


# Container Mysql
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - laravel_app


# Container Redis
  redis:
    image: redis:alpine
    container_name: redis-container
    restart: always
    volumes:
      - redis-data:/data
    networks:
      - laravel_app


# Container Mailhog
  mailhog:
    image: mailhog/mailhog:latest
    container_name: mailhog-container
    restart: always
    networks:
      - laravel_app


# Container Nginx
  nginx:
    image: nginx:alpine
    container_name: nginx-container
    restart: always
    volumes:
      - .:/var/www/laravel
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - laravel-1
      - laravel-2
      - laravel-3
      - laravel-4
      - laravel-5
    networks:
      - laravel_app


# Container Ngrok
  ngrok:
    image: ngrok/ngrok:latest
    container_name: ngrok-container
    restart: always
    environment:
      - NGROK_AUTHTOKEN=2pSWLJmWY9h42RfQacngPjR3NV7_46y2urodZwKejHA8iHSKi
    command: http nginx:80
    networks:
      - laravel_app
    depends_on:
      - nginx
    ports:
      - "4040:4040"

networks:
  laravel_app:
    driver: bridge

volumes:
  mysql-data:
    driver: local
  redis-data:
    driver: local
